### ISSUE TITLE
Epigraph issues

### ISSUE THREAD

**Issue by drgrigg** [compdelta/walter-de-la-mare_the-return#2]
The first character in the `<cite>` should be an em-dash, not a hyphen.

Also, I'm not sure why you needed to add `-epub-hyphens: none;` to the CSS for the epigraph?

**Comment by drgrigg** [comment]
Scratch the second comment above, that's how our manual has it!

**Comment by drgrigg** [comment]
I'm still only seeing a hyphen in the cite tag, rather than an em-dash.

**Comment by compdelta** [comment]
Replaced hyphen with em-dash in cite tag now.
